import type { Metadata } from "next";
// import { useOrderStore } from "@/lib/store/orderStore";
import Providers from "./providers";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { Itim } from "next/font/google";
import FetchOrders from "@/components/FetchOrders";
import FetchHoldOrders from "@/components/FetchHoldOrders";
const itim = Itim({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "POS_Yaimali",
  description: "Generated by Kaitoon",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${itim.className} antialiased bg-gay-700/40 bg-opacity-70 dark:bg-black dark:bg-opacity-50`}
      >
        <Providers>
          <ThemeProvider>
            <Navbar />
            <FetchOrders />
            {children}
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
