import type { Metadata } from "next";
// import { useOrderStore } from "@/lib/store/orderStore";
import Providers from "./providers";
import "./globals.css";
import "./hold-clear-btn.css";
import "./paybtn.css";
import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { Itim } from "next/font/google";
import "./deletetocartbtn.css";

const itim = Itim({
  subsets: ["latin"],
  weight: ["400"],
});
import { ConfirmDialog } from "@/components/confirm-dialog";
export const metadata: Metadata = {
  title: "POS_Yaimali",
  description: "Generated by Kaitoon",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${itim.className} antialiased bg-gay-700/40 bg-opacity-70 dark:bg-black dark:bg-opacity-50`}
      >
        <Providers>
          <ThemeProvider>
            <Navbar />
            {children}
            <ConfirmDialog />
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
